auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Archie's Web Sit
url:              http://archiex.github.com
feed:             /atom.xml
author:
    name:         Archie
    twitter:      twitter.com/beiyuu
description:      "Archie\'s Blog"
author_info:      <a href="http://archiex.github.com/about">Archie</a>
disqus_username:  archiex

copyright:
    - Design by <a href="http://archiex.github.com/about" title="Archie" target="_blank">Archie</a> &copy; Copyright 2012
